services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ev-charging-tracker-app
        restart: unless-stopped
        volumes:
            - ./var:/app/var
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=web"
            - "traefik.http.routers.ev-charging-tracker-app.rule=Host(`evtracking.loickpostel.fr`)"
            - "traefik.http.routers.ev-charging-tracker-app.entrypoints=websecure"
            - "traefik.http.routers.ev-charging-tracker-app.tls=true"
            - "traefik.http.routers.ev-charging-tracker-app.tls.certresolver=loickpostelresolver"
            - "traefik.http.services.ev-charging-tracker-app.loadbalancer.server.port=80"
        depends_on:
            - db
        networks:
            - web
            - internal

    db:
        image: postgres:18.0-alpine
        container_name: ev-charging-tracker-db
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - ev-charging-tracker-data:/var/lib/postgresql
        networks:
            - internal

volumes:
    ev-charging-tracker-data:

networks:
    web:
        external: true
    internal:
        driver: bridge
