services:
    db:
        image: postgres:18.0-alpine
        container_name: db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - ev-charging-tracker-local-data:/var/lib/postgresql
        restart: unless-stopped

volumes:
    ev-charging-tracker-local-data:
