services:
    db:
        image: postgres:17.5
        container_name: db_prod
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - pg-data:/var/lib/postgresql/data
        restart: unless-stopped
        networks:
            - app

    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - APP_ENV=prod
        container_name: app
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        environment:
            - APP_ENV=prod
            - DOMAIN=${DOMAIN:-localhost}
            - FRANKENPHP_CONFIG=worker ./public/index.php
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - app

volumes:
    pg-data:
    caddy_data:
    caddy_config:

networks:
    app:
