services:
    db:
        image: postgres:17.5
        container_name: db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - pg-data:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    pg-data:
